### ISSUE TITLE
stockfish_20011801_x64.exe is not stopping after the game is over.

### ISSUE THREAD

**Issue by ManWalkingInRain** [RuolinZheng08/renpy-chess#16]
Each time I make a move, one "stockfish_20011801_x64.exe" being added to the list. Even if the game is over, these tasks still continue to run.. And this eats so much ram :/
![Adssız](https://user-images.githubusercontent.com/56637132/120865505-d4bf3880-c596-11eb-94c6-509a2370aeb6.png)

**Comment by RuolinZheng08** [comment]
Thanks for the detailed report! I also saw this behavior on Mac.
In my newest commit, I did call `stockfish_engine.quit()` when the game ends, according to the doc linked to below, but the stockfish processes persist. Could be a bug in their implementation?
https://python-chess.readthedocs.io/en/v0.23.10/

If you have any capacity and wouldn't mind looking into it, feel free to. I'm still trying to figure out whether their `quit` function does what it should do.

**Comment by ManWalkingInRain** [comment]
@RuolinZheng08 I searched a bit but couldn't find a solution too.. Also, i'm not very good at python :/

**Comment by RuolinZheng08** [comment]
I think I've fixed this for both the 7.3.5 version and the 7.4 version, both for PvP and PvC. Please feel free to test all combinations out and let me know if you still experience issues.
a6f0b783a666a9bdd9e898313782ead305b525d6
4394af31228d7912da778ceef8de0379a6965c5b
