### ISSUE TITLE
Pawn promotion doesn't seem to work

### ISSUE THREAD

**Issue by feilaung** [RuolinZheng08/renpy-chess#25]
![screenshot](https://github.com/user-attachments/assets/979d4143-1804-4031-9151-3685a4237ff2)
Hello! Promotion GUI is showing up but it doesn't activate anything. When I try to reach the end of the board it only shows notify (as in given screenshot) although the promotion is selected...

**Comment by RuolinZheng08** [comment]
Hmmm. For me to reproduce this bug, can you elaborate on the steps you took or record a video/GIF? Did you simply click on pawn -> click on promotion piece type -> click on destination square? Or did you unselect the pawn at any point and then attempt to promote?

**Comment by RuolinZheng08** [comment]
Should be fixed. Please reopen if the issue persists on the newest version.

**Comment by feilaung** [comment]
It works now. Thank you.
